config/routes.rb
Bookshop::Application.routes.draw do
  
  resources :settings

  resources :invoices

  resources :transactions

  resources :accounts

  get "home/index"

  root :to => 'home#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :account
  has_many :transaction
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :ok }
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :is_sent %><br />
    <%= f.text_field :is_sent %>
  </div>
  <div class="field">
    <%= f.label :send_method %><br />
    <%= f.text_field :send_method %>
  </div>
  <div class="field">
    <%= f.label :date_sent %><br />
    <%= f.datetime_select :date_sent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Date</th>
    <th>Is sent</th>
    <th>Send method</th>
    <th>Date sent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoices.each do |invoice| %>
  <tr>
    <td><%= invoice.customer_id %></td>
    <td><%= invoice.date %></td>
    <td><%= invoice.is_sent %></td>
    <td><%= invoice.send_method %></td>
    <td><%= invoice.date_sent %></td>
    <td><%= link_to 'Show', invoice %></td>
    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
    <td><%= link_to 'Destroy', invoice, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @invoice.customer_id %>
</p>

<p>
  <b>Date:</b>
  <%= @invoice.date %>
</p>

<p>
  <b>Is sent:</b>
  <%= @invoice.is_sent %>
</p>

<p>
  <b>Send method:</b>
  <%= @invoice.send_method %>
</p>

<p>
  <b>Date sent:</b>
  <%= @invoice.date_sent %>
</p>


<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>