config/routes.rb
Bookshop::Application.routes.draw do
  
  resources :settings

  resources :invoices

  resources :transactions

  resources :accounts

  get "home/index"

  root :to => 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :invoice
  
  def transactions_made 
    Transaction.where( 'from_customer= #{id}' ).order('data ASC') 
  end
  
  def transactions_received 
    Transaction.where( 'to_customer= #{id}' ).order('data ASC') 
  end
  
  def transactions 
    Transaction.where( 'from_customer = :id AND to_customer = :id', { :id => id } )
               .order('date ASC')
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :first_name2 %><br />
    <%= f.text_field :first_name2 %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :address_line1 %><br />
    <%= f.text_field :address_line1 %>
  </div>
  <div class="field">
    <%= f.label :address_line2 %><br />
    <%= f.text_field :address_line2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :email2 %><br />
    <%= f.text_field :email2 %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.text_field :is_active %>
  </div>
  <div class="field">
    <%= f.label :is_customer %><br />
    <%= f.text_field :is_customer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>First name</th>
    <th>First name2</th>
    <th>Surname</th>
    <th>Address line1</th>
    <th>Address line2</th>
    <th>City</th>
    <th>State</th>
    <th>Postcode</th>
    <th>Email</th>
    <th>Email2</th>
    <th>Is active</th>
    <th>Is customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.first_name %></td>
    <td><%= account.first_name2 %></td>
    <td><%= account.surname %></td>
    <td><%= account.address_line1 %></td>
    <td><%= account.address_line2 %></td>
    <td><%= account.city %></td>
    <td><%= account.state %></td>
    <td><%= account.postcode %></td>
    <td><%= account.email %></td>
    <td><%= account.email2 %></td>
    <td><%= account.is_active %></td>
    <td><%= account.is_customer %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @account.first_name %>
</p>

<p>
  <b>First name2:</b>
  <%= @account.first_name2 %>
</p>

<p>
  <b>Surname:</b>
  <%= @account.surname %>
</p>

<p>
  <b>Address line1:</b>
  <%= @account.address_line1 %>
</p>

<p>
  <b>Address line2:</b>
  <%= @account.address_line2 %>
</p>

<p>
  <b>City:</b>
  <%= @account.city %>
</p>

<p>
  <b>State:</b>
  <%= @account.state %>
</p>

<p>
  <b>Postcode:</b>
  <%= @account.postcode %>
</p>

<p>
  <b>Email:</b>
  <%= @account.email %>
</p>

<p>
  <b>Email2:</b>
  <%= @account.email2 %>
</p>

<p>
  <b>Is active:</b>
  <%= @account.is_active %>
</p>

<p>
  <b>Is customer:</b>
  <%= @account.is_customer %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>